### ISSUE TITLE
Display footnotes on web pages and links from the article body go to the footnote

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm#136]
## Problem / Motivation

- WHO wants this?
- WHEN and WHERE do they want it?
- WHAT do they want?
- WHY do they want this?

Many of the IJM journal articles have footnotes. The footnote content is not current displayed on the web pages, and they are not included in the article JSON after an article XML has been parsed into JSON. The `<xref>` tags in the article body are already converted to `<a>` tags linking the sentence to the footnote, the link does not lead anywhere.

After some discussion today, the first attempt to display footnotes on each article web page is to append a section named `Footnotes` to the end of the article body. The footnotes for appendices can be ignored in this first attempt.

A first outcome of this issue to to provide a pull request containing a handful of articles including footnotes for review, and the result can be evaluated.

## Proposed solution

- Is like this
- And like this

As discussed in the meeting, with some additional details, in the first try @gnott intends to try:

- Parse the `<fn>` XML tag content into article JSON using the `elife-tools` parsing library. I think it would be good to create a new parsing function, `footnotes_json()`, rather than altering the existing `body_json()` funciton which produces article body JSON
- In the `ijm` branch of `bot-lax-adaptor` (https://github.com/elifesciences/bot-lax-adaptor/tree/ijm) is where the `footnotes_json` can be added to the end of the `body_json`.

Other notes:

- Footnotes in tables will remain the same
- PDF files can remain unchanged
- This simplest solution is a way to avoid having to change the JSON schema, if it is possible to avoid it

## Clarification needed and assumptions

- A question
- An assumption

There's a potential complication due to how `elife-tools` has newer releaes, and the `ijm` branch of `bot-lax-adaptor` uses an older version of `elife-tools`. Ideally if IJM could use the latest version of the parsing library then it can avoid maintaining a separate branch just for IJM. The impacts of using newer parser code includes, at least, the re-ordering of the `preferred` author names, and this may be a side effect of updating to the new parser library, if the results are compatible and acceptable to IJM.

---

## Tasks

The list of tasks below can be expanded later

- [x] Parse `<fn>` tags from the XML
- [x] Include footnotes JSON into the article JSON
- [x] Test the footnotes output on the journal locally
- [x] Create a PR with some example articles including footnotes for review
- [x] Adjust the plan
- [x] Finally, generate JSON for all the articles into a new PR
- [x] Commit changes to code so these footnotes are always generated for IJM

## Technical notes
- We could use this technology
- More notes or suggestions

## User interface / Wireframes

A screenshot can be provided after initial testing.

cc @matteorichiardi @BlueReZZ @FAtherden-eLife and please share with others who may like to follow.

**Comment by gnott** [comment]
I tried parsing some footnotes content today using some drafted parsing code. It was working well so I continued with trying to generate footnotes for all the article XML I have in my local folder. In doing so I uncovered examples which led me to improve the code to where it is fairly reliable.

The logic turned out to be in summary: find the `<fn-group>` tag which is directly under the `<back>` tag (so it ignores `<fn-group>` inside a `<table-wrap>`), and only if the `<fn-group>` tag does not have a `@content-type` attribute.

In order for each `<a>` link in the body content to jump down to the specific footnote, the `<fn>` tag's `@id` is used on a content `section` id, and the section's title is taken from the text of the `<label> tag.

I generated JSON for preview which is in the https://github.com/microsimulation/ijm/tree/footnotes-preview branch. Do you have a way to preview this without needing to merge or deploy it yet?

The result I'm seeing is the `Footnotes` section appears in the left side navigation list, and the section is expanded if you click one of the footnote links.

Here's how an article looks when I preview on my system (article `00010`)

![image](https://user-images.githubusercontent.com/1779115/145315346-8d3d1e6a-61bc-4924-9bb9-7263ba3eb101.png)

@pbronka, I wonder if you are able to look at the content in the new branch and arrange to try it out and please provide feedback? Thanks!

**Comment by pbronka** [comment]
This looks great, thanks a lot @gnott ! Apologies for the delay on my side, will aim to set up a local copy of the website tomorrow and test it within the next couple of days and update this tracker.

**Comment by pbronka** [comment]
I have now set up a local copy of the website and previewed the version with footnotes - I think it looks really good, very nice way to solve this issue, thanks! 

Sorry for the delay - I had some troubles with Docker first and then building the website: it turns out that if you clone this repository using GitHub Desktop, it changes line endings in the files, and the "make dev" no longer works. But without GitHub Desktop "make dev" actually works really well, much simpler than the previous version I used. 

I tested articles at random, and everything works well. Two minor observations:

1. In article ijm-00231, Footnote 10 is not "clickable", as it is inside of a section heading. If there was a straightforward fix it would be nice to have that capability, but otherwise I think the best solution is to make sure that going forward we don't allow footnotes in sections headings etc.
2. Would it make sense to order the "Footnotes" section before "References" instead of before appendices? For example, article ijm-00234 has footnotes in appendices, so the footnotes section is introduced before they appear in text. But at the same time it might be easier to quickly access footnotes if they are just below the main body - @matteorichiardi, do you have any preference?

**Comment by gnott** [comment]
Thanks for the review feedback @pbronka!

On point 1, I agree it is probably best to avoid placing a footnote link in a section heading, because the section headings are not converted to HTML the same as is done for paragraph content, and all tags are ignored in section headings

Point 2, the placement of the footnote content in this first preview is the easiest to do, by adding it to the article body. In order to have it displayed on a alternate location on a article page, it would be easier if the footnote content was its own high level data structure. One or two things would be needed in that case, first certain the journal website code would need to be changed to display the footnote content where you would like it to appear, and second would be to define in the data schema the property holding the footnote content (this may be optional, since I've noticed you can add any data and it will not interfere with validation if there is no definition for orphan data).

I could change where the footnote content appears in the article JSON, but I would leave it to you to figure out the journal web page display logic and any schema change required to allow the content to be shown, if you choose to not have it added to the end of the article body.

**Comment by matteorichiardi** [comment]
Hi Graham,
first, thanks a lot for this, it looks great. Re. those two issues, I would
go for the simplest solution, i.e., if I understand it correctly, (1) not
allowing footnotes in headings (even if we lose one footnote or two in the
html archive), and (2) display footnotes at the end of the text body
(hyperlinks make it easy to move around the text).
Best wishes,
Matteo

**Comment by gnott** [comment]
I created the PR https://github.com/microsimulation/ijm/pull/139 from the branch of footnote content. If there's no additional changes required and you like it, I will commit the code which adds the footnote content to the article JSON for IJM articles.

**Comment by pbronka** [comment]
I merged the PR into the master version of the website. Everything seems to be working as expected and we now have footnotes on the website - so I think this can be closed - thank you again @gnott for coming up with and implementing an excellent solution!

**Comment by gnott** [comment]
Thanks, I'm glad the suggested fix was acceptable. I'll finish up with the final task for me to commit the code which generates the JSON output on my side.

**Comment by gnott** [comment]
I think this is done now code-wise. This branch continues to be the one I used to generate JSON https://github.com/elifesciences/bot-lax-adaptor/tree/ijm. It depends on a particular commit on a new branch of elife-tools to include footnotes json https://github.com/elifesciences/elife-tools/tree/ijm

Eventually it will be a good idea to use the latest elifetools version so a separate branch does not need to be maintained, for now I think you can continue to use the older branches until it becomes difficult to maintain them separately.
