### ISSUE TITLE
Add steps into CI pipeline to run Selenium tests

### ISSUE THREAD

**Issue by rtudvasev** [microsimulation/ijm#36]
## Subtasks
- [x] Dockerize tests
- [x] Add step into pipeline that runs ijm site and builds test container
- [x] Add step into pipeline that runs tests themselves
- [x] Add  step into pipeline that checks reports and decides to continue or not with deployment
